["protostar.config"]
protostar_version = "0.1.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
incentivizedERC20 = [
    "./contracts/protocol/tokenization/base/incentivizedERC20.cairo",
]

