["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
a_token = [
    "contracts/protocol/tokenization/a_token.cairo",
]
pool = [
    "./contracts/protocol/pool/pool.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]

[profile.devnet.protostar.deploy]
gateway-url = "http://127.0.0.1:5050/"